about:
  author: 'Mick Hua'
  date: '2022-08-13'

files:
#Correct File
  - filepath: c:/Users/mickh/OneDrive/01_Developer/02_Python/louder-data-eng-task/example1.csv

#Incorrect Test File that is not of type csv
  - filepath: c:/Users/mickh/OneDrive/01_Developer/02_Python/louder-data-eng-task/example2.txt

#Incorrect Test File Missing "Reporting Fields"
  - filepath: c:/Users/mickh/OneDrive/01_Developer/02_Python/louder-data-eng-task/example3.csv

#Incorrect Test File Missing "Grand Total"
  - filepath: c:/Users/mickh/OneDrive/01_Developer/02_Python/louder-data-eng-task/example4.csv

#Incorrect Test File Missing "Account ID"
  - filepath: c:/Users/mickh/OneDrive/01_Developer/02_Python/louder-data-eng-task/example5.csv
